version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: devcontainer
    environment:
      - PGPASSWORD=postgres # make psql not prompt
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    user: user

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: